### ISSUE TITLE
q1/test_e5.py/test_e5b_wraps 

### ISSUE THREAD

**Issue by michaldeutch** [advanced-system-design/exercise-2#1]
Hi @dan-gittik ,
Not sure if I'm correct, but I think that the part:
`_test_wraps(e5b.exception_safe)`

should be altered to:
`_test_wraps(e5b.exception_safe())`

Thanks,
Michal.

**Comment by dan-gittik** [comment]
`exception_safe` should be what we called a "semi-parametrized" decorator, i.e. a decorator that would work like this:

```
@exception_safe
def f():
    pass
```

Which means the test is actually correct.
